### ISSUE TITLE
I see the workspaces view on pressing the super key.

### ISSUE THREAD

**Issue by AnishDe12020** [pop-os/gnome-shell-extension-pop-cosmic#195]
So I got an update for the cosmic shell today and then my keyboard shortcuts behaviour has become really weird. Before pressing the super key would pull up the pop os launcher (the search thing) but not it pulls up the workspaces view. This has gotten pretty annoying. I wish we get a fix either in the form of a revert or at least the option to revert back to what it was. Also weirdly enough, when i log out and log back in, it comes back to normal. But then there is an issue with that to. After 30mins-1hr again some or the other short cut gets messed up. I hope this is fixed soon

**Comment by brs17** [comment]
@AnishDe12020 , have you tried restarting your machine? I experienced this very same issue. I went into Settings->Desktop->General to see if playing around with the Super Key Action toggle would change anything, and it didn't. I then restarted my machine and now the super key has resorted back to the Launcher as I had desired.

EDIT/ADDITION:
After I updated `pop-cosmic` to `1.1.0~1628527572~21.04~3eda9bb`, I did reload the shell with `alt`+`f2`, `r`.

**Comment by AnishDe12020** [comment]
I haven't tried restarting but i did try logging back out and logging back in but that is sort of temporary. After using the computer for sometimes, again the problem shows up.

**Comment by brs17** [comment]
@AnishDe12020 yes, I can now confirm that the issue does come back after some time.

**Comment by AnishDe12020** [comment]
Thanks for the follow up. I hope the bug is fixed soon!!!

**Comment by brs17** [comment]
> Thanks for the follow up. I hope the bug is fixed soon!!!

It is being investigated currently!

**Comment by ids1024** [comment]
This should be fixed now in the latest package update.

**Comment by AnishDe12020** [comment]
Quick fix: You do not need to restart your computer or log out and log back in (which closes all your programs) to fix the issue. Restarting the gnome shell with `alt f2` and then typing `r` fixes the issue under 5 seconds. This can be considered a temporary fix for now i think

**Comment by jmaargh** [comment]
Can I clarify exactly what people are seeing here? What I'm understanding is:

- You have the super key set to open the launcher
- After some time of using the machine, the super key instead starts opening workspaces (and not the launcher? or both at the same time?)
- After restarting the shell  (either directly, or by logging out or rebooting), the original behaviour is restored for while, after which workspaces starts getting opened by Super again

Is this correct?

When the issue appears, does re-setting the "Super key action" option in "settings" fix it (at least temporarily)?

**Comment by AnishDe12020** [comment]
> Can I clarify exactly what people are seeing here? What I'm understanding is:
> 
> * You have the super key set to open the launcher
> * After some time of using the machine, the super key instead starts opening workspaces (and not the launcher? or both at the same time?)
> * After restarting the shell  (either directly, or by logging out or rebooting), the original behaviour is restored for while, after which workspaces starts getting opened by Super again
> 
> Is this correct?
> 
> When the issue appears, does re-setting the "Super key action" option in "settings" fix it (at least temporarily)?

- After some time of using the machine, the super key instead starts opening only the workspaces menu

Rest all is correct (at least for me)

I haven't tried re-setting the super key option in settings yet. I will try it the next time the issue occurs and let you know

**Comment by brs17** [comment]
> When the issue appears, does re-setting the "Super key action" option in "settings" fix it (at least temporarily)?

> I went into Settings->Desktop->General to see if playing around with the Super Key Action toggle would change anything, and it didn't.

**Comment by jacobgkau** [comment]
> After some time of using the machine, the super key instead starts opening workspaces (and not the launcher? or both at the same time?)

On one machine that was experiencing the issue, I was able to trigger it faster by locking and unlocking. (Doing that triggered the issue immediately.)

**Comment by nigurr** [comment]
It works as expected until first time screen locks out. Once the system locks out and when we login back, it default to workspace behaviour and nothing can be done. Only way to fix so far is, log out and re-login. This is like most unstable experience in recent times from Pop os

**Comment by AnishDe12020** [comment]
The issue is fixed so I am closing it

**Comment by Sylk** [comment]
Just installed Cosmic today, and saw this issue. I played around with the toggle to see if it would resolve anything, and then updated through the pop-shop. However the issue persisted. Even after trying the Alt + F2 with command r, it didn't seem to fix. The only way to get it to work is using super + / but I dislike that heavily.
